### ISSUE TITLE
Can't set Role using `s?addrole`

### ISSUE THREAD

**Issue by ThiccJello** [FCCouncil/Moonglow#14] opened 2018-09-12 00:55 UTC
**Discord Information**
Discord Username with Discriminator: ThiccJello
#7759
If you can provide, what is your user ID:
What is your role in the Fortnite Community server:
Regular
**Describe the bug**
When trying to use the command "s?addrole" it doesn't recognize the role of others
**To Reproduce**
#1 Type s?addrole (usename) (and then a role you wish to add)
#2 Shadowshard gives an error saying "I couldn't find that role"

**Expected behavior**
Should add role to the specified player/
**Screenshots**

**Additional context**

**Comment by mattsilver1** [comment] 2018-09-12 01:02
Thank you for the report, we'll be working on this piece of shit command shortly.

**Comment by mattsilver1** [comment] 2018-09-12 14:02
Pull request #36 by @TheSkele27 may have fixed this issue, we are are waiting to test the command to ensure that the issue is resolved in the next upcoming hours. I expect to update you within at least 3-5 hours.

**Comment by mattsilver1** [comment] 2018-09-12 20:59
After testing, this bug wasn't fixed by #36. We will be performing more additional investigations and will provide an update shortly.

**Comment by mattsilver1** [comment] 2018-09-16 19:56
Will not fix.

**Closed by mattsilver1** 2018-09-16 19:56 UTC
Labels: bug, wontfix
